defaults:
  - _self_

model:
  loss:
    l_comp: 0.5
    l_s: 0.01
    l_tv: 0.02
  optim:
    lr: 5e-5
    weight_decay: 1e-2
  proj_dim: 256
  nt_xent:
    temperature: 0.07

data:
  rebuild_ds: False
  train:
    dataset: "cnn"
    batch_size: 128
    num_workers: 4
    subset: 1.0
    shuffle: True
  eval:
    dataset: "wikiann"
    batch_size: 32
    num_workers: 1
    subset: 0.1
    shuffle: True

train:
  retrain: False
  epochs: 10
  
eval:
  eval_only: False
  verbose: False
  thresh: 0.5
  samples:
    num: 10
    show: True

device: "cuda"

dora:
  exclude: ["eval.eval_only","train.retrain","eval.verbose","data.eval.dataset", "eval.samples"]