defaults:
  - _self_

model:
  attention_augment: False
  loss:
    l_comp: 0.5       # weight for adversary loss
    l_s: 0.01         # sparsity regularizer
    l_tv: 0.02        # total variation regularizer
    tau: 0.07         # InfoNCE temperature (was model.nt_xent.temperature)
  optim:
    lr: 5e-5
    weight_decay: 1e-2
    lr_adv: 5e-5
    weight_decay_adv: 1e-2

data:
  rebuild_ds: False
  train:
    dataset: "cnn"
    batch_size: 128
    num_workers: 4
    subset: 1.0
    shuffle: True
  eval:
    dataset: "wikiann"
    batch_size: 32
    num_workers: 1
    subset: 1.0
    shuffle: True

train:
  retrain: True
  epochs: 10
  grad_clip: 1.0

eval:
  eval_only: False
  verbose: False
  thresh: 0.5
  samples:
    num: 10
    show: True

device: "cpu"

dora:
  exclude: ["train.retrain","eval", "data.rebuild_ds"]
