runtime:
  device: cpu
  num_threads: 8

model:
  encoder:
    family: sbert
    name: sentence-transformers/all-MiniLM-L6-v2
  loss:
    sweep_range: [0.1, 1.0, 100]

selector:
  signature: "bd694009"
  tau: 1.0
  
eval:
  dataset: glue/stsb
  split: validation
  batch_size: 64
  max_length: 128
  random_selector:
    runs: 5
    seed: 0

