runtime:
  device: cpu
  num_threads: 8

model:
  encoder:
    family: sbert
    name: sentence-transformers/all-MiniLM-L6-v2

selector:
  signature: "17e9488d"
  tau: 1.0
  
eval:
  dataset: glue/stsb
  split: validation
  batch_size: 64
  max_length: 128
  rho_sweep:
    start: 0.2
    end: 0.8
    steps: 10
  random_selector:
    runs: 5
    seed: 0

