defaults:
  - _self_

model:
  sbert_name: "sentence-transformers/all-MiniLM-L6-v2"
  loss:
    l_rec: 1.0       # weight for reconstruction loss
    l_comp: 0.0       # weight for adversary loss
    l_s: 1.0        # sparsity regularizer
    l_tv: 0.0        # total variation regularizer
    tau: 0.07         # InfoNCE temperature (was model.nt_xent.temperature)
  optim:
    lr: 5e-5
    weight_decay: 1e-2
    lr_adv: 5e-5
    weight_decay_adv: 1e-2
    betas: [0.9, 0.999]

data:
  shared:
    rebuild: False
    max_length: 512
    batch_size: 256
    num_workers: 8
    shuffle: True
    tokenizer_name: "sentence-transformers/all-MiniLM-L6-v2"
    sentence_model_name: "sentence-transformers/all-MiniLM-L6-v2"
  train:
    dataset: "ud"
    split: "train"
    config: null
    subset: 1.0
  eval:
    dataset: "ud"
    config: null
    split: "validation"
    subset: 1.0

train:
  eval_only: False
  eval_epoch: True
  epochs: 30
  lr: 1e-3
  weight_decay: 0.0
  grad_clip: 1.0
  checkpoint: "model.pth"

runtime:
  num_threads: 8
  device: "cuda"
  token_parallelism: False
  grid_mode: False

dora:
  exclude: ["train.retrain", "eval.report.*", "eval.eval_only", "eval.verbose", "data.rebuild_ds", "slurm.*", "runtime.grid_mode"]

array: 0

slurm:
  partition: "boost_usr_prod"
  gpus: 1
  mem_per_gpu: 32
  time: 240          # minutes
  cpus_per_gpu: 8
  setup:
    - "module load python/3.11.7"
    - "source $HOME/RatCon/.venv/bin/activate"
    - "export SLURM_CPU_BIND=none"
    - "export HF_HOME=$HOME/hf-cache"
    - "export TRANSFORMERS_CACHE=$HF_HOME/transformers"
    - "export HF_DATASETS_CACHE=$HF_HOME/datasets"
    - "export HF_HUB_OFFLINE=1"
    - "export TRANSFORMERS_OFFLINE=1"
