defaults:
  - _self_
  - override: default

model:
  selector:
    hard_type: "probabilistic_top_k"
  loss:
    l_e: 1.0
    hard: false
    s_target: 0.3
    tau: 1.0
    l_tv: 0.0
    sweep_range: [0.1, 1.0, 10]
  optim:
    lr: 1e-3
    weight_decay: 1e-2
    betas: [0.9, 0.999]

data:
  shuffle: false
  max_length: 512
  dataset: "mr"
  config: null
  subset: 1.0
  encoder:
    family: "sbert"
    name: null

train:
  epochs: 30
  no_train: false

runtime:
  grid: false
  threads: 32
  interop_threads: 8
  device: "cpu"
  token_parallelism: false
  data:
    rebuild: false
    batch_size: 256
    num_workers: 2
  eval:
    short_log: false
    log_examples: 0
    hard: true

# ------------------------------------------------------------
# STS-B evaluation (matches metric script EXACTLY)
# ------------------------------------------------------------

eval:
  split: "validation"      # glue/stsb split
  batch_size: 256
  max_length: 128

  random_selector:
    runs: 5
    seed: 1234

dora:
  exclude:
    - "slurm.*"
    - "runtime.*"
    - "train.no_train"

array: 0

slurm:
  partition: "boost_usr_prod"
  gpus: 1
  mem_per_gpu: 32
  time: 240
  cpus_per_gpu: 8
  setup:
    - "module load python/3.11.7"
    - "source $HOME/RatCon/.venv/bin/activate"
    - "export SLURM_CPU_BIND=none"
    - "export HF_HOME=$HOME/hf-cache"
    - "export TRANSFORMERS_CACHE=$HF_HOME/transformers"
    - "export HF_DATASETS_CACHE=$HF_HOME/datasets"
    - "export HF_HUB_OFFLINE=1"
    - "export TRANSFORMERS_OFFLINE=1"